### ISSUE TITLE
Booting the SD DDP without an SD card will lock on the boot splash screen

### ISSUE THREAD

**Issue by JohnLundy** [epearsoe/Coleco-ADAM-SD-DDP#2]
Booting the SD DDP without an SD card will lock on the boot splash screen. It would be nice to have an error message appear on the display when an SD card is not inserted and would possibly help troubleshoot a bad SD card or connection/hardware issues for users.

**Comment by epearsoe** [comment]
This should be fixed in version 1.1.  It wasn't actually locking up. It was displaying "No SD Card" but I had forgotten to set the text color to white so it was printing black on black. The new version should display the message now and give you the option to insert an SD card and press the 'Mount' button to reinit the SD card.
